### ISSUE TITLE
seeing weird mysql error, api is fine tho

### ISSUE THREAD

**Issue by cohenaj194** [ff14-advanced-market-search/saddlebag-with-pockets#191]
<img width="1088" alt="image" src="https://user-images.githubusercontent.com/17516896/214444080-5ef9353f-510c-4a47-a10a-3443ccf8fe4a.png">

the api is fine tho seems to be something with the most recent pr

**Comment by oldben87** [comment]
Oh dear!

**Comment by oldben87** [comment]
I think the issue is that when the form is closed the transition & disclosure components are taken out of the DOM, so the form fields are not submitted to the back end, I think to fix it we need to instead of giving the elements a ```display: none;``` they need to be shrunk so they aren't visible, but are still submitted to the form properly.
